"?column?"
"CREATE TABLE answer_options (order_number integer, created_at timestamp with time zone, question_id uuid, id uuid, is_correct boolean, option_text text);"
"CREATE TABLE applications (cover_letter text, resume_url text, status text, id uuid, created_at timestamp with time zone, updated_at timestamp with time zone, job_id uuid, candidate_id uuid);"
"CREATE TABLE assessment_templates (id uuid, created_by uuid, updated_at timestamp with time zone, title text, description text, created_at timestamp with time zone);"
"CREATE TABLE assessments (id uuid, updated_at timestamp with time zone, ai_feedback text, weaknesses ARRAY, strengths ARRAY, status text, created_at timestamp with time zone, created_by uuid, overall_score numeric, completion_time timestamp with time zone, start_time timestamp with time zone, candidate_id uuid, template_id uuid);"
"CREATE TABLE candidate_assessments (status text, created_at timestamp with time zone, assessment_id uuid, candidate_id uuid, id uuid, updated_at timestamp with time zone);"
"CREATE TABLE dashboard_widget_settings (widget_key text, is_visible boolean, order_number integer, widget_type text, description text, allowed_roles ARRAY, widget_name text, id uuid);"
"CREATE TABLE jobs (location text, id uuid, salary_range text, title text, created_at timestamp with time zone, description text, created_by uuid, updated_at timestamp with time zone, requirements text);"
"CREATE TABLE manager_approvals (approved_by uuid, created_at timestamp with time zone, updated_at timestamp with time zone, manager_id uuid, status text, id uuid);"
"CREATE TABLE page_access_rules (page_name text, allowed_roles ARRAY, updated_at timestamp with time zone, created_at timestamp with time zone, is_enabled boolean, id uuid, page_path text);"
"CREATE TABLE profiles (avatar_url text, role USER-DEFINED, full_name text, updated_at timestamp with time zone, created_at timestamp with time zone, id uuid, email text, company text, position text);"
"CREATE TABLE questions (id uuid, assessment_template_id uuid, evaluation_criteria jsonb, order_number integer, created_at timestamp with time zone, updated_at timestamp with time zone, question_text text, question_type text);"
"CREATE TABLE responses (score numeric, question_id uuid, assessment_id uuid, updated_at timestamp with time zone, created_at timestamp with time zone, selected_option_id uuid, ai_feedback text, video_url text, text_response text, id uuid);"
"CREATE TABLE salesperson_managers (id uuid, salesperson_id uuid, manager_id uuid, created_at timestamp with time zone);"
"CREATE TABLE shop_visits (id uuid, created_at timestamp with time zone, updated_at timestamp with time zone, shop_name text, audio_url text, location jsonb, notes text, status text, salesperson_id uuid);"
"CREATE TABLE training_progress (completed_at timestamp with time zone, completed boolean, quiz_score integer, quiz_completed boolean, last_position double precision, watched_percentage integer, video_id uuid, user_id uuid, id uuid, last_updated_at timestamp with time zone);"
"CREATE TABLE training_quiz_options (option_text text, id uuid, question_id uuid, is_correct boolean, order_number integer);"
"CREATE TABLE training_quiz_questions (video_id uuid, created_at timestamp with time zone, id uuid, quiz_number integer, question text);"
"CREATE TABLE training_quiz_results (score integer, id uuid, user_id uuid, video_id uuid, total_questions integer, created_at timestamp with time zone);"
"CREATE TABLE training_video_progress (updated_at timestamp with time zone, video_id uuid, created_at timestamp with time zone, last_position double precision, progress_percentage integer, id uuid, user_id uuid);"
"CREATE TABLE training_videos (title text, thumbnail_url text, id uuid, has_quiz boolean, category text, order_number integer, created_at timestamp with time zone, description text, video_url text, created_by uuid);"